routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/sh', function () {
    return view('blog.category');
});

Route::get('/', 'BlogController@index')->name('index');
Route::get('/show/{id}/{slug}', 'BlogController@show')->name('show');
Route::get('/categories/{id}', 'BlogController@category')->name('category');
Route::get('/komen', 'CommentController@index')->name('comment.index');
Route::post('/show/{id}', 'CommentController@store')->name('comment.store');

Route::middleware('auth')->group(function () {

    Route::get('/admin', 'HomeController@index');


    Route::prefix('/admin')->name('admin.')->group(function () {

        Route::resource('/categories', 'CategoryController');

        Route::resource('/articles', 'ArticleController');

        Route::resource('/users', 'UserController');
    });
});

Route::get('/login', 'AuthController@login');
Route::post('/login', 'AuthController@loginProccess');
Route::get('/register', 'AuthController@register');
Route::post('/register', 'AuthController@registrationProccess');
Route::post('/logout', 'AuthController@logout');

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\Article;
use App\Model\Category;
use App\Model\User;
use App\Model\Tag;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class ArticleController extends Controller
{
    function __construct()
    {
        $this->model = new Article();
        $this->imgPath = public_path('img');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('viewAny', $this->model);

        if (auth()->user()->role == 'author') {
            $articles = $this->model->where('user_id', auth()->user()->id)->orderBy('created_at', 'desc')->paginate(10);
        } else {
            $articles = $this->model->orderBy('created_at', 'desc')->paginate(10);
        }

        return view('admin.article.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', $this->model);

        $categories = Category::all();
        $tags = Tag::all();
        return view('admin.article.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', $this->model);

        $request->validate([
            'title' => 'required|max:255',
            'category_id' => 'required',
            'content' => 'required',
            'photo' => 'required',
            'tag' => 'required',
        ]);

        if ($request->photo) {
            $request = $this->uploadImage($request);
        }

        $request->merge([
            'user_id' => Auth::user()->id,
            'slug' => Str::of($request->title)->slug('-'),
        ]);

        $article = $this->model->create($request->all());;


        if ($article) {
            $tagnames = $request->tag;
            foreach ($tagnames as $tagname) {
                $tag = Tag::firstOrCreate(['name' => $tagname]);
            }
            $pico = Tag::whereIn('name', $tagnames)->get()->pluck('id');
            $article->Tag()->sync($pico);
        }

        return redirect('/admin/articles');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $articles = $this->model->find($id);
        $this->authorize('update', $articles);
        $categories = Category::all();
        $tags = Tag::all();

        return view('admin.article.edit', compact('articles', 'categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required|max:255',
            'category_id' => 'required',
            'content' => 'required',
            'user_id' => 'required',
            'tag' => 'required',
        ]);

        $model = $this->model->find($id);
        $this->authorize('update', $model);

        if ($request->photo) {
            $this->removeImage($model->image);
            $request = $this->uploadImage($request);
        }

        $article = $this->model->find($id);

        if ($article) {
            $tagnames = $request->tag;
            foreach ($tagnames as $tagname) {
                $tag = Tag::firstOrCreate(['name' => $tagname]);
            }
            $pico = Tag::whereIn('name', $tagnames)->get()->pluck('id');
            $article->Tag()->sync($pico);
        }

        $this->model->find($id)->update($request->all());

        return redirect('/admin/articles');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = $this->model->find($id);

        $this->authorize('delete', $model);
        $this->removeImage($model->image);

        $model->delete();

        return redirect('/admin/articles');
    }

    // Untuk Image

    public function uploadImage($request)
    {
        $img = $request->file('photo');
        $newName = time() . '.' . $img->getClientOriginalExtension();

        $img->move($this->imgPath, $newName);

        $request->merge([
            'image' => $newName,
        ]);

        return $request;
    }

    public function removeImage($img)
    {
        $fullPath = $this->imgPath . '/' . $img;

        if ($img && file_exists($fullPath)) {
            unlink($fullPath);
        }
    }

    public function handleTag(Request $request, Article $article)
    {
        $tagnames = $request->tag;
        foreach ($tagnames as $tagname) {
            Tag::firstOrCreate(['name' => $tagname])->save();
        }
        $tags = Tag::whereIn('name', $tagnames)->get()->pluck('id');
        $article->Tag()->sync($tags);
    }
}

resources/views/admin/article/create.blade.php
@extends('layout.dash')

@section('title', 'Create Article')

@section('head-script')
<script src="https://cdn.tiny.cloud/1/oixc359s0v223g7r2nfb661iddynhcunyatkpwv4f5tjp8dy/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')

@if($errors->any())
<hr>
<ul>
    @foreach($errors->all() as $error)
    <li>{{ $error }}</li>
    @endforeach
</ul>
<hr>
@endif

<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Create New Article</h4>
                <p class="card-article">Create article for your blog</p>
            </div>
            <div class="card-body">
                <form action="/admin/articles/" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col">
                            <div class="form-group" style="margin-top: 43px;">
                                <label class="bmd-label-floating">Title</label>
                                <input type="text" class="form-control" name="title" value="{{ old('title') }}">
                            </div>
                        </div>

                        <div class="col">
                            <div class="form-group">
                                <label class="bmd-label-floating">Category</label>
                                <select class="form-control" name="category_id" id="">
                                    <option value="">-- Select Category --</option>
                                    @foreach($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <textarea name="content" id="tiny">{{ old('content') }}</textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="">Tags</label>
                                <select name="tag[]" multiple="multiple" class="form-control" id="tags">
                                    @foreach ($tags as $tag)
                                    <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="">
                                <label>Image
                                    <input type="file" name="photo" value="{{ old('photo') }}" accept="image/*">
                                </label>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn py-2 btn-primary pull-right">Create</button>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection


@section('end-script')
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script>
    tinymce.init({
        selector: 'textarea#tiny', // change this value according to your HTML
        plugin: 'a_tinymce_plugin',
        a_plugin_option: true,
        a_configuration_option: 400,
        height: 600,
    });

    $("#tags").select2({
        tags: true,
        tokenSeparators: [',', ' ']
    })
</script>
@endsection

resources/views/admin/article/edit.blade.php
@extends('layout.dash')

@section('title', 'Edit Article')

@section('head-script')
<script src="https://cdn.tiny.cloud/1/oixc359s0v223g7r2nfb661iddynhcunyatkpwv4f5tjp8dy/tinymce/5/tinymce.min.js"
    referrerpolicy="origin"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')

@if($errors->any())
<hr>
<ul>
    @foreach($errors->all() as $error)
    <li>{{ $error }}</li>
    @endforeach
</ul>
<hr>
@endif

<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Edit New Article</h4>
                <p class="card-article">Edit article for your blog</p>
            </div>
            <div class="card-body">
                <form action="{{ route('admin.articles.update', ['article' => $articles->id]) }}" method="POST">
                    @csrf
					@method('PUT')
                    <div class="row">
                        <div class="col">
                            <div class="form-group" style="margin-top: 43px;">
                                <label class="bmd-label-floating">Title</label>
                                <input type="text" class="form-control" name="title" value="{{ old('title', $articles->title) }}">
                            </div>
                        </div>

                        <div class="col">
                            <div class="form-group">
                                <label class="bmd-label-floating">Category</label>
                                <select class="form-control" name="category_id" id="">
                                    <option value="">-- Select Category --</option>
                                    @foreach($categories as $category)
                                    <option value="{{ $category->id }}" {{ $category->id == $articles->category_id ? 'selected' : '' }}>{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <textarea name="content" id="tiny">{{ old('content', $articles->content) }}</textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="">Tags</label>
                                <select name="tag[]" multiple="multiple" class="form-control" id="tags">
                                    @foreach ($tags as $index => $tag)
                                        <option value="{{ $tag->id }}" {{ $articles->Tag()->pluck('tag_id')->contains($tag->id) ? 'selected': '' }}>{{ $tag->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="">
                                <label>Image
                                    <input type="file" name="photo" accept="image/*">
                                </label>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" value="{{ auth()->user()->id }}" name="user_id">
                    <button type="submit" class="btn py-2 btn-primary pull-right">Update</button>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection


@section('end-script')
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script>
    tinymce.init({
        selector: 'textarea#tiny', // change this value according to your HTML
        plugin: 'a_tinymce_plugin',
        a_plugin_option: true,
        a_configuration_option: 400,
        height: 600,
    });

    $("#tags").select2({
        tags: true,
        tokenSeparators: [',', ' ']
    })

</script>
@endsection

resources/views/admin/article/index.blade.php
@extends('layout.dash')

@section('title', 'Articles')
@section('head-script')
<style>
    label {
        white-space: nowrap;
    }

    .dataTables_filter {
        text-align: right;
    }
</style>
@endsection

@section('content')

<div class="card">
    <div class="card-header card-header-primary card-header-icon">
        <div class="card-icon"><i class="material-icons">assignment</i></div>
        <div class="d-flex justify-content-between mt-2">
            <h4 class="display-4 d-block text-dark">Articles</h4>
            <a href="/admin/articles/create" class="btn btn-primary">Create New Article</a>
        </div>
    </div>
    <div class="card-body">
        <table id="dtable" class="table table-striped table-no-bordered table-hover dataTable dtr-inline">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Category</th>
                    <th width="30%">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($articles as $article )
                <tr>
                    <td>{{ $article->title }}</td>
                    <td>{{ $article->user->name }}</td>
                    <td>{{ $article->category->name }}</td>
                    <td>
                        <a href="{{ route('admin.articles.edit', ['article' => $article->id]) }}" class="btn btn-warning btn-sm d-inline-block">Edit</a>
                        <form method="post" class="d-inline-block" action="{{ route('admin.articles.destroy', $article->id) }}">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger btn-sm">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection

@section('end-script')
<script>
    $(document).ready(function() {
        $('#dtable').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [
                [10, 25, 50, -1],
                [10, 25, 50, "All"]
            ],
            responsive: true,
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search records",
            }
        });

        var table = $('#datatable').DataTable();

        // Edit record
        table.on('click', '.edit', function() {
            $tr = $(this).closest('tr');
            var data = table.row($tr).data();
            alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
        });

        // Delete a record
        table.on('click', '.remove', function(e) {
            $tr = $(this).closest('tr');
            table.row($tr).remove().draw();
            e.preventDefault();
        });

        //Like record
        table.on('click', '.like', function() {
            alert('You clicked on Like button');
        });
    });
</script>
@endsection