routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/sh', function () {
    return view('blog.category');
});

Route::get('/', 'BlogController@index')->name('index');
Route::get('/show/{id}/{slug}', 'BlogController@show')->name('show');
Route::get('/categories/{id}', 'BlogController@category')->name('category');
Route::get('/komen', 'CommentController@index')->name('comment.index');
Route::post('/show/{id}', 'CommentController@store')->name('comment.store');

Route::middleware('auth')->group(function () {

    Route::get('/admin', 'HomeController@index');


    Route::prefix('/admin')->name('admin.')->group(function () {

        Route::resource('/categories', 'CategoryController');

        Route::resource('/articles', 'ArticleController');

        Route::resource('/users', 'UserController');
    });
});

Route::get('/login', 'AuthController@login');
Route::post('/login', 'AuthController@loginProccess');
Route::get('/register', 'AuthController@register');
Route::post('/register', 'AuthController@registrationProccess');
Route::post('/logout', 'AuthController@logout');

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\Category;
use App\Model\Article;

class CategoryController extends Controller
{
    function __construct()
    {
        $this->model = new Category();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('viewAny', $this->model);
        $categories = $this->model->all();

        return view('admin.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', $this->model);
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', $this->model);
        $request->validate([
            'name' => 'required|max:255',
        ]);

        Category::create($request->all());
        return redirect('/admin/categories');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->authorize('update', $this->model);
        $categories = $this->model->find($id);

        return view('admin.category.edit', compact('categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->authorize('update', $this->model);
        $request->validate([
            'name' => 'required|max:255',
        ]);

        $this->model->find($id)->update($request->all());

        return redirect('/admin/categories');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = $this->model->find($id);
        $this->authorize('update', $model);

        Article::where('category_id', $id)->update([
            'category_id' => 1,
        ]);

        $model->delete();
        return redirect('/admin/categories');
    }
}

resources/views/admin/category/create.blade.php
@extends('layout.dash')

@section('title', 'Create Category')

@section('content')

@if($errors->any())
<hr>
<ul>
    @foreach($errors->all() as $error)
    <li>{{ $error }}</li>
    @endforeach
</ul>
<hr>
@endif

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Create New Category</h4>
                <p class="card-category">Create category for your article</p>
            </div>
            <div class="card-body">
                <form action="/admin/categories/" method="POST">
                    @csrf
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <label class="bmd-label-floating">Category Name</label>
                                <input type="text" class="form-control" value="{{ old('name') }}" name="name">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn py-2 btn-primary pull-right">Create</button>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/category/edit.blade.php
@extends('layout.dash')

@section('title', 'Edit Category')

@section('content')

@if($errors->any())
<hr>
<ul>
	@foreach($errors->all() as $error)
	<li>{{ $error }}</li>
	@endforeach
</ul>
<hr>
@endif

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Edit This Category</h4>
                <p class="card-category">Edit your category</p>
            </div>
            <div class="card-body">
                <form action="{{ route('admin.categories.update', ['category' => $categories->id]) }}" method="POST">
                    @csrf
					@method('PUT')
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <label class="bmd-label-floating">Category Name</label>
                                <input type="text" class="form-control" name="name" value="{{ old('name', $categories->name) }}">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn py-2 btn-primary pull-right">Edit</button>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/category/index.blade.php
@extends('layout.dash')

@section('title', 'Categories')
@section('head-script')
<style>
    label {
        white-space: nowrap;
    }

    .dataTables_filter {
        text-align: right;
    }

</style>
@endsection

@section('content')

<div class="card">
    <div class="card-header card-header-primary card-header-icon">
        <div class="card-icon"><i class="material-icons">assignment</i></div>
        <div class="d-flex justify-content-between mt-2">
            <h4 class="display-4 d-block text-dark">Categories</h4>
            <a href="/admin/categories/create" class="btn btn-primary">Create New Category</a>
        </div>
    </div>
    <div class="card-body">
        <table id="dtable" class="table table-striped table-no-bordered table-hover dataTable dtr-inline">
            <thead>
                <tr>
                    <th>Category Name</th>
                    <th width="30%">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($categories as $category )
                <tr>
                    <td>{{ $category->name }}</td>
                    <td>
                        <a href="{{ route('admin.categories.edit', ['category' => $category->id]) }}"
                            class="btn btn-warning btn-sm d-inline-block">Edit</a>
                        <form method="post" class="d-inline-block"
                            action="{{ route('admin.categories.destroy', $category->id) }}">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger btn-sm">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection

@section('end-script')
<script>
    $(document).ready(function () {
        $('#dtable').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [
                [10, 25, 50, -1],
                [10, 25, 50, "All"]
            ],
            responsive: true,
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search records",
            }
        });

        var table = $('#datatable').DataTable();

        // Edit record
        table.on('click', '.edit', function () {
            $tr = $(this).closest('tr');
            var data = table.row($tr).data();
            alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
        });

        // Delete a record
        table.on('click', '.remove', function (e) {
            $tr = $(this).closest('tr');
            table.row($tr).remove().draw();
            e.preventDefault();
        });

        //Like record
        table.on('click', '.like', function () {
            alert('You clicked on Like button');
        });
    });

</script>
@endsection