routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/sh', function () {
    return view('blog.category');
});

Route::get('/', 'BlogController@index')->name('index');
Route::get('/show/{id}/{slug}', 'BlogController@show')->name('show');
Route::get('/categories/{id}', 'BlogController@category')->name('category');
Route::get('/komen', 'CommentController@index')->name('comment.index');
Route::post('/show/{id}', 'CommentController@store')->name('comment.store');

Route::middleware('auth')->group(function () {

    Route::get('/admin', 'HomeController@index');


    Route::prefix('/admin')->name('admin.')->group(function () {

        Route::resource('/categories', 'CategoryController');

        Route::resource('/articles', 'ArticleController');

        Route::resource('/users', 'UserController');
    });
});

Route::get('/login', 'AuthController@login');
Route::post('/login', 'AuthController@loginProccess');
Route::get('/register', 'AuthController@register');
Route::post('/register', 'AuthController@registrationProccess');
Route::post('/logout', 'AuthController@logout');

resources/views/layout/dash.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="/mtadmin/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="/mtadmin/assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    @yield('title') | CMS1
  </title>
  <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="/mtadmin/assets/css/material-dashboard.css?v=2.1.20" rel="stylesheet" />
  @yield('head-script')
</head>

<body class="">
  <div class="wrapper ">
    @include('layout.sidebar')
    <div class="main-panel">
      <!-- Navbar -->
      @include('layout.navbar')
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
          @yield('content')
        </div>
      </div>
      <footer class="footer">
        @include('layout.footer')
      </footer>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="/mtadmin/assets/js/core/jquery.min.js"></script>
  <script src="/mtadmin/assets/js/core/popper.min.js"></script>
  <script src="/mtadmin/assets/js/core/bootstrap-material-design.min.js"></script>
  <script src="/mtadmin/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!--  Plugin for Sweet Alert -->
  <script src="/mtadmin/assets/js/plugins/sweetalert2.js"></script>
  <!-- Forms Validations Plugin -->
  <script src="/mtadmin/assets/js/plugins/jquery.validate.min.js"></script>
  <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
  <script src="/mtadmin/assets/js/plugins/bootstrap-selectpicker.js"></script>
  <!--  DataTables.net Plugin, full documentation here: https://datatables.net/  -->
  <script src="/mtadmin/assets/js/plugins/jquery.dataTables.min.js"></script>
  <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
  <script src="/mtadmin/assets/js/plugins/jasny-bootstrap.min.js"></script>
  <!-- Library for adding dinamically elements -->
  <script src="/mtadmin/assets/js/plugins/arrive.min.js"></script>
  <!-- Chartist JS -->
  <script src="/mtadmin/assets/js/plugins/chartist.min.js"></script>
  <!--  Notifications Plugin    -->
  <script src="/mtadmin/assets/js/plugins/bootstrap-notify.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="/mtadmin/assets/js/material-dashboard.js?v=2.1.2" type="text/javascript"></script>
  <!-- Material Dashboard DEMO methods, don't include it in your project! -->
  <script src="/mtadmin/assets/demo/demo.js"></script>
  @yield('end-script')
</body>

</html>

resources/views/layout/footer.blade.php
<div class="container-fluid">
	<nav class="float-left">
	<ul>
		<li>
		<a href="https://www.creative-tim.com">
			Creative Tim
		</a>
		</li>
		<li>
		<a href="https://creative-tim.com/presentation">
			About Us
		</a>
		</li>
		<li>
		<a href="http://blog.creative-tim.com">
			Blog
		</a>
		</li>
		<li>
		<a href="https://www.creative-tim.com/license">
			Licenses
		</a>
		</li>
	</ul>
	</nav>
	<div class="copyright float-right">
	&copy;
	<script>
		document.write(new Date().getFullYear())
	</script>, made with <i class="material-icons">favorite</i> by
	<a href="https://www.instagram.com/adine_pamungkas/" target="_blank">Adine Pamungkas</a> for a better web.
	</div>
</div>

resources/views/layout/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <a class="navbar-brand" href="javascript:;">@yield('title')</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
                <div class="input-group no-border">
                    <input type="text" value="" class="form-control" placeholder="Search...">
                    <button type="submit" class="btn btn-white btn-round btn-just-icon">
                        <i class="material-icons">search</i>
                        <div class="ripple-container"></div>
                    </button>
                </div>
            </form>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="javascript:;">
                        <i class="material-icons">dashboard</i>
                        <p class="d-lg-none d-md-block">
                            Stats
                        </p>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">notifications</i>
                        <span class="notification">5</span>
                        <p class="d-lg-none d-md-block">
                            Some Actions
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Mike John responded to your email</a>
                        <a class="dropdown-item" href="#">You have 5 new tasks</a>
                        <a class="dropdown-item" href="#">You're now friend with Andrew</a>
                        <a class="dropdown-item" href="#">Another Notification</a>
                        <a class="dropdown-item" href="#">Another One</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">person</i>
                        <p class="d-lg-none d-md-block">
                            Account
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                        <a class="dropdown-item" href="{{ route('admin.users.show', ['user' => auth()->user()->id]) }}">Profile</a>
                        <a class="dropdown-item" href="#">Settings</a>
                        <div class="dropdown-divider"></div>
                        <form action="/logout" method="post">
                            @csrf
                            <button class="dropdown-item" href="#">Log out</button>
                        </form>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/layout/sidebar.blade.php
<?php

$dashboard = [
	'title' => 'Dashboard',
	'url' => '/admin',
  'model' =>App\Model\Home::class,
	'icon' => 'dashboard',
];

$category = [
	'title' => 'Categories',
	'url' => '/admin/categories',
  'model' =>App\Model\Category::class,
	'icon' => 'category',
];

$article = [
	'title' => 'Article',
	'url' => '/admin/articles',
  'model' =>App\Model\Article::class,
	'icon' => 'article',
];

$user = [
	'title' => 'User',
	'url' => '/admin/users',
  'model' =>App\Model\User::class,
	'icon' => 'person',
];

$menus = [$dashboard, $category, $article, $user];

$currentPath = '/' . request()->path();

?>
<div class="sidebar" data-color="purple" data-background-color="white" data-image="/mtadmin/assets/img/sidebar-1.jpg">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
    -->
      <div class="logo"><a href="/admin" class="simple-text logo-normal">
          {{ auth()->user()->name }} | CMS
        </a></div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          @foreach ($menus as $index => $menu )
            @can('viewAny', $menu['model'])
              <li class="nav-item {{ $currentPath == $menu['url'] ? 'active' : '' }}">
                <a class="nav-link" href="{{ $menu['url'] }}">
                  <i class="material-icons">{{ $menu['icon'] }}</i>
                  <p>{{ $menu['title'] }}</p>
                </a>
              </li>
            @endcan
          @endforeach
        </ul>
      </div>
    </div>