routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/sh', function () {
    return view('blog.category');
});

Route::get('/', 'BlogController@index')->name('index');
Route::get('/show/{id}/{slug}', 'BlogController@show')->name('show');
Route::get('/categories/{id}', 'BlogController@category')->name('category');
Route::get('/komen', 'CommentController@index')->name('comment.index');
Route::post('/show/{id}', 'CommentController@store')->name('comment.store');

Route::middleware('auth')->group(function () {

    Route::get('/admin', 'HomeController@index');


    Route::prefix('/admin')->name('admin.')->group(function () {

        Route::resource('/categories', 'CategoryController');

        Route::resource('/articles', 'ArticleController');

        Route::resource('/users', 'UserController');
    });
});

Route::get('/login', 'AuthController@login');
Route::post('/login', 'AuthController@loginProccess');
Route::get('/register', 'AuthController@register');
Route::post('/register', 'AuthController@registrationProccess');
Route::post('/logout', 'AuthController@logout');

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\User;
use App\Model\Article;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    function __construct()
    {
        $this->model = new User();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('viewAny', $this->model);
        $users = $this->model->all();

        return view('admin.user.index', compact('users'));
    }

    public function show($id)
    {
        $user = $this->model->find($id);
        $this->authorize('view', $user);

        return view('admin.user.profile', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', $this->model);
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', $this->model);
        $request->validate([
            'name' => 'required|max:255',
            'email' => 'required|max:255',
            'password' => 'required|max:255',
            'role' => 'required',
        ]);

        $endcriptPassword = Hash::make($request->password);

        $request->merge([
            'password' => $endcriptPassword,
        ]);

        User::create($request->all());

        return redirect('/admin/users');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->model->find($id);
        $this->authorize('update', $user);

        return view('admin.user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = $this->model->find($id);
        $this->authorize('update', $user);

        $request->validate([
            'name' => 'required|max:255',
            'email' => 'required|max:255',
            'role' => 'required',
        ]);

        $request->merge(['password' => $user->password]);
        $user->update($request->all());
        return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = $this->model->find($id);
        $this->authorize('delete', $user);

        if ($user->id != 1) {
            Article::where('user_id', $id)->update([
                'user_id' => 1,
            ]);

            if (Auth::user()->role == 'admin') {
                $user->delete();
                return redirect()->back();
            } else {
                Auth::logout();
                $user->delete();
                return redirect('/login');
            }
        } else {
            return redirect()->back();
        }
    }
}

resources/views/admin/user/create.blade.php
@extends('layout.dash')

@section('title', 'Create User')

@section('content')

@if($errors->any())
<hr>
<ul>
    @foreach($errors->all() as $error)
    <li>{{ $error }}</li>
    @endforeach
</ul>
<hr>
@endif

<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Create New User</h4>
                <p class="card-user">Create user for your article</p>
            </div>
            <div class="card-body">
                <form action="/admin/users/" method="POST">
                    @csrf
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label class="bmd-label-floating">User Name</label>
                                <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label class="bmd-label-floating">User E-Mail</label>
                                <input type="email" class="form-control" name="email" value="{{ old('email') }}">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label class="bmd-label-floating">User Password</label>
                                <input type="password" class="form-control" name="password">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <select name="role" class="form-control">
                                    <option value="">-- Select user Role --</option>
                                    <option value="admin">Admin</option>
                                    <option value="editor">Editor</option>
                                    <option value="author">Author</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn py-2 btn-primary pull-right">Create</button>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layout.dash')

@section('title', 'Create User')

@section('content')

@if($errors->any())
<hr>
<ul>
    @foreach($errors->all() as $error)
    <li>{{ $error }}</li>
    @endforeach
</ul>
<hr>
@endif

<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Create New User</h4>
                <p class="card-user">Create user for your article</p>
            </div>
            <div class="card-body">
                <form action="{{ route('admin.users.update', ['user' => $user->id]) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label class="bmd-label-floating">User Name</label>
                                <input type="text" class="form-control" name="name" value="{{ old('name', $user->name) }}">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label class="bmd-label-floating">User E-Mail</label>
                                <input type="email" class="form-control" name="email" value="{{ old('email', $user->email) }}">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <select name="role" class="form-control">
                                    <option value="">-- Select user Role --</option>
                                    <option value="admin" {{ $user->role == 'admin' ? 'selected' : '' }}>Admin</option>
                                    <option value="editor" {{ $user->role == 'editor' ? 'selected' : '' }}>Editor
                                    </option>
                                    <option value="author" {{ $user->role == 'author' ? 'selected' : '' }}>Author
                                    </option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn py-2 btn-primary pull-right">Update</button>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/index.blade.php
@extends('layout.dash')

@section('title', 'Users')
@section('head-script')
<style>
    label {
        white-space: nowrap;
    }

    .dataTables_filter {
        text-align: right;
    }

</style>
@endsection

@section('content')

<div class="card">
    <div class="card-header card-header-primary card-header-icon">
        <div class="card-icon"><i class="material-icons">assignment</i></div>
        <div class="d-flex justify-content-between mt-2">
            <h4 class="display-4 d-block text-dark">Users</h4>
            <a href="/admin/users/create" class="btn btn-primary">Create New User</a>
        </div>
    </div>
    <div class="card-body">
        <table id="dtable" class="table table-striped table-no-bordered table-hover dataTable dtr-inline">
            <thead>
                <tr>
                    <th>User Name</th>
                    <th>User E-Mail</th>
                    <th>User Role</th>
                    <th width="30%">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($users as $user )
                <tr>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->role }}</td>
                    <td>
                        <a href="{{ route('admin.users.edit', ['user' => $user->id]) }}"
                            class="btn btn-warning btn-sm d-inline-block">Edit</a>
                        <form method="post" class="d-inline-block"
                            action="{{ route('admin.users.destroy', $user->id) }}">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger btn-sm">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection

@section('end-script')
<script>

    $(document).ready(function () {
        $('#dtable').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [
                [10, 25, 50, -1],
                [10, 25, 50, "All"]
            ],
            responsive: true,
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search records",
            }
        });

        var table = $('#datatable').DataTable();

        // Edit record
        table.on('click', '.edit', function () {
            $tr = $(this).closest('tr');
            var data = table.row($tr).data();
            alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
        });

        // Delete a record
        table.on('click', '.remove', function (e) {
            $tr = $(this).closest('tr');
            table.row($tr).remove().draw();
            e.preventDefault();
        });

        //Like record
        table.on('click', '.like', function () {
            alert('You clicked on Like button');
        });
    });

</script>
@endsection

resources/views/admin/user/profile.blade.php
@extends('layout.dash')

@section('title', 'Profile')

@section('content')
<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Edit Profile</h4>
                <p class="card-category">Complete your profile</p>
            </div>
            <div class="card-body">
                <form action="{{ route('admin.users.update', ['user' => $user->id]) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label class="bmd-label-floating">User Name</label>
                                <input type="text" class="form-control" name="name" value="{{ old('name', $user->name) }}">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label class="bmd-label-floating">User E-Mail</label>
                                <input type="email" class="form-control" name="email" value="{{ old('email', $user->email) }}">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <select name="role" class="form-control">
                                    <option value="">-- Select user Role --</option>
                                    <option value="admin" {{ $user->role == 'admin' ? 'selected' : '' }}>Admin</option>
                                    <option value="editor" {{ $user->role == 'editor' ? 'selected' : '' }}>Editor
                                    </option>
                                    <option value="author" {{ $user->role == 'author' ? 'selected' : '' }}>Author
                                    </option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn py-2 btn-primary pull-right">Update</button>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card card-profile">
            <div class="card-avatar">
                <a href="javascript:;">
                    <img class="img" src="https://mir-s3-cdn-cf.behance.net/project_modules/disp/0e08b316030025.5629a19202e12.png" />
                </a>
            </div>
            <div class="card-body">
                <h6 class="card-category text-gray">CEO / Co-Founder</h6>
                <h4 class="card-title">Alec Thompson</h4>
                <p class="card-description">
                    Don't be scared of the truth because we need to restart the human foundation in truth And I love you
                    like Kanye loves Kanye I love Rick Owens’ bed design but the back is...
                </p>
                <a href="javascript:;" class="btn btn-primary btn-round">Follow</a>
            </div>
        </div>
    </div>
</div>
@endsection